### ISSUE TITLE
Paul McGann crashes

### ISSUE THREAD

**Issue by prydonius** [drwrose/doctors#1]
The Paul McGann state seems to crash my pebble. The minutes update, but any button I press causes my pebble to restart.

I noticed you committed a fix for crashing on the new firmware, was that supposed to address this issue, or is it something different? According to the app store, I am on the latest version.

**Comment by drwrose** [comment]
Hi prydonius,

Oops, my apologies, I didn't get this message until now!  Are you still having problems with this watchface, or is it finally working?

**Comment by prydonius** [comment]
Hey @drwrose, it's been working great since 2.15 I think!

Thanks :)
